version: '3.9'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      proxy-network:
        aliases: []

    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./htpasswd:/etc/nginx/htpasswd"
      - "./vhost.d:/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy.conf:/etc/nginx/proxy.conf"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs:/etc/nginx/certs"


  letsencrypt-nginx-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

networks:
  proxy-network :
     driver: bridge